#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port7,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveRight, encoder)
#pragma config(Motor,  motor4,           ,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,           ,             tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	turnLeft(25, degrees, 100);
	moveMotor(motor11, 1.3, rotations, 100);
	stopMotor(motor11);
	repeatUntil (getTimer(T1, seconds) == 3) {
		setMultipleMotors(-100, motor11, motor5, noMotor, noMotor);
	}
	stopMultipleMotors(motor11, motor5, noMotor, noMotor);
}
